
set -e
DEVSIM_CONFIG=appveyor
GENERATOR="$1"
AOPTION="$2"
BUILDDIR="$3"
CONDA_PREFIX="$4"

mkdir -p ${BUILDDIR}
(cd ${BUILDDIR}; cmake -G "${1}" -A $2 -DDEVSIM_CONFIG=${DEVSIM_CONFIG} -DPYTHON3=ON  -DMKL_PARDISO=ON -DANACONDA_PATH=${CONDA_PREFIX} -DBUILDDIR=${BUILDDIR} ..)

