#IF (APPLE)
#SET (CMAKE_EXE_LINKER_FLAGS "-framework CoreFoundation")
#SET (CMAKE_EXE_LINKER_FLAGS "-framework CoreFoundation -flat_namespace")
ADD_DEFINITIONS(-DTCL_THREADS -fvisibility=hidden)
#ENDIF (APPLE)
#IF (${DEVSIM_CONFIG} STREQUAL "osx_10.9")
SET (FLEX /usr/bin/flex)
SET (BISON /usr/bin/bison)
SET (PYTHON_ARCHIVE "/usr/lib/libpython2.7.dylib")
SET (PYTHON_INCLUDE "/System/Library/Frameworks/Python.framework/Headers"
)

SET (TCL_STUB /usr/lib/libtclstub8.5.a)
SET (BLAS_ARCHIVE  /usr/lib/libblas.dylib /usr/lib/libcblas.dylib /usr/lib/liblapack.dylib)
SET (EXTERNAL_LIB ${PROJECT_SOURCE_DIR}/external)
SET (SUPERLULOCATE  ${EXTERNAL_LIB}/SuperLU_4.3)
SET (SUPERLU_INCLUDE ${SUPERLULOCATE}/SRC)
SET (SUPERLU_ARCHIVE ${SUPERLULOCATE}/lib/libsuperlu_4.3_x86_64.a)
SET (TCL_INCLUDE "/usr/include")
SET (TCL_ARCHIVE "/usr/lib/libtcl8.5.dylib" -ldl)
SET (SQLITE3_ARCHIVE /usr/lib/libsqlite3.dylib)
SET (SQLITE3_INCLUDE "/usr/include")
SET (CGNS_ARCHIVE ${EXTERNAL_LIB}/cgnslib/lib/libcgns.a)
SET (CGNS_INCLUDE ${EXTERNAL_LIB}/cgnslib/include)
SET (ZLIB_INCLUDE "/usr/include")
SET (ZLIB_ARCHIVE "/usr/lib/libz.dylib")
SET (SYMDIFF_ARCHIVE ${EXTERNAL_LIB}/symdiff/lib/libsymdiff_static.a)
SET (SYMDIFF_INCLUDE ${EXTERNAL_LIB}/symdiff/include)
#ENDIF (${DEVSIM_CONFIG} STREQUAL "osx_10.9")

