#IF (APPLE)
#SET (CMAKE_EXE_LINKER_FLAGS "-framework CoreFoundation")
#SET (CMAKE_EXE_LINKER_FLAGS "-framework CoreFoundation -flat_namespace")
ADD_DEFINITIONS(-DTCL_THREADS -fvisibility=hidden)
#ENDIF (APPLE)
#IF (${DEVSIM_CONFIG} STREQUAL "osx_10.9")
SET (FLEX /usr/bin/flex)
SET (BISON /usr/bin/bison)
SET (PYTHON27_ARCHIVE "-lpython2.7")
SET (PYTHON27_INCLUDE "/usr/include/python2.7")

SET (TCL_STUB /usr/lib/libtclstub8.5.a)
SET (BLAS_ARCHIVE  -weak-lblas -weak-llapack)
SET (EXTERNAL_LIB ${PROJECT_SOURCE_DIR}/external)
SET (SUPERLULOCATE  ${EXTERNAL_LIB}/SuperLU_4.3)
SET (SUPERLU_INCLUDE ${SUPERLULOCATE}/SRC)
SET (SUPERLU_ARCHIVE ${SUPERLULOCATE}/lib/libsuperlu_4.3_x86_64.a)
SET (TCL_INCLUDE "/usr/include")
SET (TCL_ARCHIVE "-ltcl8.5" -ldl)
SET (SQLITE3_ARCHIVE "-lsqlite3")
SET (SQLITE3_INCLUDE "/usr/include")
SET (CGNS_ARCHIVE ${EXTERNAL_LIB}/cgnslib/lib/libcgns.a)
SET (CGNS_INCLUDE ${EXTERNAL_LIB}/cgnslib/include)
SET (ZLIB_INCLUDE "/usr/include")
SET (ZLIB_ARCHIVE "-lz")
SET (SYMDIFF_ARCHIVE ${EXTERNAL_LIB}/symdiff/lib/libsymdiff_static.a)
SET (SYMDIFF_INCLUDE ${EXTERNAL_LIB}/symdiff/include)
SET (ADD_LINKER_FLAGS " -flat_namespace")
#ENDIF (${DEVSIM_CONFIG} STREQUAL "osx_10.9")

