on:
  push:
    branches:
      - "r2.9.2"
jobs:
  example_matrix:
    strategy:
      # also support macos, linux arm64
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        # TODO: use specific submodules for platform
        with:
          submodules: true
      - name: build linux x86_64
        # TODO: make sure each part is built with the proper concurrency
        if: steps.isSmoke.output.test == true
        run: |
          echo "RUNNER OS"  "$RUNNER_OS" "${{ runner.os }}"
          #bash ./scripts/build_docker_manylinux_2_28.sh test_tag;
